# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kscreen

# >> macros
# << macros

Summary:    API to control screen settings
Version:    2.0.0
Release:    1
Group:      System/Base
License:    LGPLv2.1+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kscreen.yaml
Source101:  kscreen-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5QuickWidgets)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  libkscreen-devel
BuildRequires:  kdbusaddons-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  ki18n-devel
BuildRequires:  kxmlgui-devel
BuildRequires:  kglobalaccel-devel

%description
API to control screen settings.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING COPYING.LGPL
%{_kf5_bindir}/kscreen-console
%{_kf5_iconsdir}/*
%{_kf5_servicesdir}/*
%{_kf5_plugindir}/*
%{_kf5_sharedir}/kcm_kscreen
# >> files
# << files
